listening-port=3478
tls-listening-port=5349
listening-ip=82.22.174.112
relay-ip=82.22.174.112
external-ip=82.22.174.112
realm=grzly.ru
server-name=grzly.ru
user=mentorlink:mentorlink2026
lt-cred-mech
fingerprint
no-cli
no-tlsv1
no-tlsv1_1
min-port=49152
max-port=49252
log-file=/var/log/coturn.log
